version: '3'

services:
  latex:
    container_name: latex2pdf
    image: texlive/texlive:latest-full
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../resume:/data
      - ../output:/output
    command: bash -c "pdflatex -output-directory=/output main.tex"

  chktex:
    container_name: linter-chktex
    image: texlive/texlive:latest-full
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../resume:/data
      - ../output:/output
